name: prerelease
on:
  push:
    branches: [master]
jobs:
  prerelease:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
