name: prerelease
on:
  push:
    branches: [master]
jobs:
  prerelease:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Configure CI Git User
        run: |
          git config --global user.email "admin@parseplatform.org"
          git config --global user.name "Parse Community"
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run prerelease
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
